name: Semantic Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

    release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-python@v2
          with:
            python-version: "3.10.8"
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Semantic Release
          run: |
            pip install python-semantic-release==7.32.2
            git config user.name github-actions
            git config user.email github-actions@github.com
            semantic-release publish
